[tool.poetry]
name = "python_gardenlinux_lib"
version = "0.1.0"
description = "Contains tools to work with the features directory of gardenlinux, for example deducting dependencies from feature sets or validating cnames"
authors = ["Malte Münch <muench@b1-systems.de>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "python_gardenlinux_lib", from="src"}]

[tool.poetry.dependencies]
python = "^3.10"
networkx = "^3.3"
PyYAML = "^6.0.2"
pytest = "^8.3.2"
gitpython = "^3.1.43"
sphinx-rtd-theme = "^2.0.0"
apt-repo = "^0.5"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
